config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :users do
    get 'sign_in', to: 'users/sessions#new'
  end

  root 'pages#homepage'

  resources :trips do
    resources :topics, only:[:new, :create]
    get 'leave', on: :member
    get 'create_auto', to: "topics#create_auto"

    resources :invites, only:[:new, :create] do
      get 'confirm', on: :member
      get 'decline', on: :member
    end
  end

  resources :surveys, only:[:show, :destroy] do
    member do
      get 'vote'
      get 'set_deadline'
      post 'send_deadline'
    end
  end

  resources :topics, only:[:edit, :update, :destroy] do
    member do
      get 'confirm'
      get 'get_suggestion'
    end
    resources :suggestions, only:[:new, :create, :destroy, :edit, :update]
  end

  get 'vote', to: "suggestions#vote"

end

app/models/trip.rb
class Trip < ActiveRecord::Base

  #### VALIDATIONS ###
  validates :name, presence: true
  validates :destination, presence: true

  #### RELATIONS ###
  has_many :trip_participants, dependent: :destroy
  has_many :users, through: :trip_participants, dependent: :destroy
  belongs_to :host, class_name: 'User', foreign_key: 'user_id'
  has_many :invites, dependent: :destroy
  has_one :survey, dependent: :destroy
  has_many :topics, dependent: :destroy
  has_many :expenses, dependent: :destroy

  geocoded_by :destination
  after_validation :geocode, if: :destination_changed?

  def get_trip_invites
    self.invites.where(confirmed: false)
  end

  def get_pending_invites_email
    invites = self.get_trip_invites.map(&:email)
    if invites.length > 1
      result = ""
      invites.each do |invitee|
        result << " #{invitee}"
      end
      return result
    else
      invites.first
    end
  end

  def get_host_full_name
    if self.host.first_name
      self.host.first_name + " " + self.host.last_name
    else
      self.host.email
    end
  end

  def compute_total_expenses
    topics = self.topics.where(status: "Closed")
    sum = 0
    topics.each do |topic|
      sum += topic.expense
    end
    return sum
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :find_trip, only:[:show, :edit, :update, :destroy, :leave]

  def index
    @trips = current_user.trips.where.not(user_id: current_user.id)
    @mytrips = policy_scope(Trip)
    @invitations = Invite.where(email: current_user.email, confirmed: false)
  end

  def new
    @trip = Trip.new
    authorize @trip
  end

  def create
    @trip = Trip.new(trip_params)
    authorize @trip
    @trip.host = current_user

    if params[:trip][:start_date].count > 1 && @trip.save
      @survey = Survey.create
      authorize @survey
      start_dates = params[:trip][:start_date]
      end_dates = params[:trip][:end_date]
      start_dates.each_with_index do |date, index|
        SurveyDate.create(start_date: start_dates[index], end_date: end_dates[index], survey_id: @survey.id)
      end
      @survey.trip_id = @trip.id
      @survey.save
      TripParticipant.create(user_id: current_user.id, trip_id: @trip.id)
      create_topics(@trip)
      redirect_to trip_path(@trip)
    elsif @trip.save
      TripParticipant.create(user_id: current_user.id, trip_id: @trip.id)
      @trip.start_date = params[:trip][:start_date][0]
      @trip.end_date = params[:trip][:end_date][0]
      @trip.save
      create_topics(@trip)
      redirect_to trip_path(@trip)
    else
      render :new
    end
  end

  def show
    @invite = Invite.new
    if @trip.survey
      @survey = @trip.survey
      @survey_dates = @survey.sort_by_votes
    end

    @topic = Topic.new
    @pending_topics = @trip.topics.where(status: "Pending")
    @closed_topics = @trip.topics.where(status: "Closed")

    @trips = [@trip]
    @hash = Gmaps4rails.build_markers(@trips) do |trip, marker|
      marker.lat trip.latitude
      marker.lng trip.longitude
    end

    @total = @trip.compute_total_expenses
    @participants = @trip.trip_participants.map{ |participant| participant.user }
    @expenses = compute_debts(@participants, @trip, @total)
  end

  def edit
    authorize @trip
  end

  def update
    authorize @trip
    if @trip.update(trip_params) && params[:trip][:start_date] && params[:trip][:start_date].count > 1
      @survey = Survey.create
      start_dates = params[:trip][:start_date]
      end_dates = params[:trip][:end_date]
      start_dates.each_with_index do |date, index|
        SurveyDate.create(start_date: start_dates[index], end_date: end_dates[index], survey_id: @survey.id)
      end
      @survey.trip_id = @trip.id
      @survey.save
      redirect_to trip_path(@trip)
    elsif @trip.update(trip_params) && params[:trip][:start_date]
      @trip.start_date = params[:trip][:start_date][0]
      @trip.end_date = params[:trip][:end_date][0]
      @trip.save
      redirect_to trip_path(@trip)
    elsif @trip.update(trip_params)
      redirect_to trip_path(@trip)
    else
      render :edit
    end
  end

  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_path }
      format.js
    end
  end

  def leave
    TripParticipant.find_by(user_id: current_user.id, trip_id: @trip.id).destroy
    if @trip.host == current_user
      @trip.host = TripParticipant.where(trip_id: @trip.id).first.user
      @trip.save
    end
    redirect_to trips_path
  end

  private

  def trip_params
    params.require(:trip).permit(:name, :destination, :start_date, :end_date)
  end

  def find_trip
    @trip = Trip.find(params[:id])
    authorize @trip
  end

  def create_topics(trip)
    authorize trip
    Topic.create(title: "Housing", status: "Pending", user_id: trip.host.id, trip_id: trip.id)
    Topic.create(title: "Transport", status: "Pending", user_id: trip.host.id, trip_id: trip.id)
  end

  def compute_debts(users, t, total)
    # User and balance
    hash_debt = {}
    # User owes balance to another User
    hash_result = {}

    users.each do |user|
      hash_debt[user] = user.compute_user_balance(t, total)
    end

    hash_positive = hash_debt.select { |k, v| v >= 0 }.sort_by { |key, value| - value }.to_h
    hash_debt = hash_debt.select { |k, v| v < 0 }.sort_by { |key, value| value }.to_h


    hash_debt.each do |ower, balance|
      debt = balance.abs

      until debt < 0.1

        hash_result[ower] = []
        hash_positive.each do |receiver, value|
          if debt > value
            debt -= value
            hash_positive[receiver] = 0
            hash_result[ower] << [receiver, value]
          else
            hash_positive[receiver] -= debt
            hash_result[ower] << [receiver, debt]
            debt = 0
          end

        end

      end
    end
    return hash_result
  end

end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_balance_expense.html.erb
<div class="container">
  <div class="row" style="margin-bottom: 5px;">
    <div class="col s12">
      <hr style="width: 100%;">
      <div class="trip-balance-user">
        <div>
          <%= ower %> <%= t('to_owe') %> <%= recipient %>
        </div>
        <div>
          <%= amount %> <%= t('currency') %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/trips/_invitation_card.html.erb
<div class="card">
  <div class="card-title">
    <%= invitation.trip.name %>
  </div>

  <div class="invitation-card-host">
    <%= t('invited_by') %> <%= invitation.full_name_of_host %>
  </div>

  <div class="invitation-card-destination">
    <i class="material-icons">location_on</i>
    <%= invitation.trip.destination %>
  </div>



  <div class="card-invite-buttons">
    <%= link_to t('decline'), decline_trip_invite_path(invitation.trip, invitation), class: "waves-effect waves-light btn invite-button-decline" %>
    <%= link_to t('confirm'), confirm_trip_invite_path(invitation.trip, invitation), class: "waves-effect waves-light btn invite-button-accept" %>
  </div>
</div>

app/views/trips/_invitation_modal.html.erb
<div id="invitation-modal" class="modal">
  <div class="modal-header">
    <h3><%= t('invite_user') %></h3>
  </div>
  <div class="modal-body">
    <%= simple_form_for [trip, invite] do |f| %>
    <label for="email"><%= t('email_invitation') %></label>
    <div class="form-address">
      <div class="form-address-first">
        <div class="mail-address-row">
          <div class="input-field" style="width: 100%;">
            <%= f.input_field :email, multiple: true, placeholder: "yourfriend@takeoff.com" %>
          </div>

          <div class="new-invitation-button">
            <i class="material-icons add-invitation-button clickable tooltipped" data-position="top" data-delay="100" data-tooltip="<%= t('email_invitation') %>">add_circle_outline</i>
          </div>
        </div>
      </div>
      <div id="mail-addresses" class="form-address"></div>
    </div>

        <div class="modal-actions">
      <%= f.hidden_field :trip, value: trip %>
      <%= f.submit t('send_invite'), class: "waves-effect waves-light btn" %>
      <%= link_to t('back'), trip_path(trip), class: "waves-effect waves-light btn" %>
    </div>
  </div>
  <% end %>
</div>

<%= content_for :js do %>
    <%= javascript_tag do %>
        $(document).ready(function(){
          $('.new-invitation-button').on("click", function(){
            var newInvitation = $('.form-address-first').html();

            $('#mail-addresses').append(newInvitation).show('slow');
            $('.add-invitation-button').last().text("remove_circle_outline").removeClass('new-invitation-button').addClass('remove-invitation-button');
            $('.remove-invitation-button').one("click", function(){

            if ($('#mail-addresses .mail-address-row').length > 1) {
                $('#mail-addresses .mail-address-row').last().remove();
            } else {
              $('#mail-addresses').slideUp();
              $('#mail-addresses .mail-address-row').last().remove();
            };
            });

          });
        });

    <% end %>
<% end %>

app/views/trips/_trip_card.html.erb
<div class="card" id="trip-id-<%= trip.id %>">

  <div class="card-title">
    <%= link_to trip.name, trip_path(trip), class: "card-title" %>
  </div>

  <div class="card-participants">
    <p><%= t('participants') %>:</p>
    <% trip.trip_participants.each do |trip_participant| %>
        <% if trip_participant.user.facebook_picture_url %>
            <%= image_tag trip_participant.user.facebook_picture_url, class: "avatar-bordered-photo" %>
        <% else %>
            <div class="avatar avatar-bordered">
              <%= trip_participant.user.render_initials %>
            </div>
        <% end %>
    <% end %>
  </div>

  <div class="card-buttons">
    <% if policy(trip).edit? %>
        <%= link_to edit_trip_path(trip) do %>
            <i class="material-icons card-icon">mode_edit</i>
        <% end %>
    <% end %>
    <% if policy(trip).destroy? %>
        <%= link_to trip, method: :delete, remote: true do %>
            <i class="material-icons card-icon">delete</i>
        <% end %>
    <% end %>
  </div>

  <div class="card-destination">
    <i class="material-icons">location_on</i>
    <%= trip.destination %>
  </div>

  <div class="card-dates">
    <% if !trip.start_date.nil? %>

        <i class="material-icons" style="margin-right: 5px;">date_range</i>
        <%= l(trip.start_date, format: :short) %> - <%= l(trip.end_date, format: :short) %>
    <% elsif trip.survey %>
        <%= link_to t('survey.show_survey'), survey_path(trip.survey), class: "card-survey-button" %>
    <% end %>
  </div>

</div>

app/views/trips/_trip_detail_body.html.erb
<div class="row">
  <div class="col s12 m6">
    <div class="trip-to-do">

      <div class="trip-summary">
        <div class="container">
          <div class="row">
            <div class="col s12 l6 trip-summary-colum">
              <h6 class="trip-topic-title">TO-DO</h6>
              <% if @trip.start_date.nil? %>
                  <div class="trip-topic-done">
                    <i class="material-icons">date_range</i>
                    <div class="trip-topic-description">
                      <%= t('date.select_dates') %>
                    </div>
                  </div>
              <% end %>
              <% if !@pending_topics.nil? %>
                <% @pending_topics.each do |topic| %>
                    <div class="trip-topic-done">
                      <% if topic.title == "Housing" %>
                          <i class="material-icons">hotel</i>
                      <% elsif topic.title == "Transport" %>
                          <i class="material-icons">flight_takeoff</i>
                      <% else %>
                          <i class="material-icons">check_box_outline_blank</i>
                      <% end %>
                      <div class="trip-topic-description">
                        <%= topic.title %>
                      </div>
                    </div>
                <% end %>
              <% end %>

            </div>
            <div class="col s12 l6">
              <h6 class="trip-topic-title">DONE</h6>
              <% if @trip.start_date %>
                  <div class="trip-topic-done">
                    <i class="material-icons">date_range</i>
                    <div class="trip-topic-description">
                      <%= l(@trip.start_date, format: :short) %> - <%= l(@trip.end_date, format: :short) %>
                    </div>
                  </div>
              <% end %>
              <% if !@closed_topics.nil? %>
                  <% @closed_topics.each do |topic| %>
                      <div class="trip-topic-done">
                        <% if topic.title == "Housing" %>
                            <i class="material-icons">hotel</i>
                        <% elsif topic.title == "Transport" %>
                            <i class="material-icons">flight_takeoff</i>
                        <% else %>
                            <i class="material-icons">check_box_outline_blank</i>
                        <% end %>
                        <div class="trip-topic-description">
                          <%= topic.title %>
                        </div>
                      </div>
                  <% end %>
              <% end %>
            </div>
          </div>
        </div>


        <% if !@closed_topics.nil? %>
            <ul>
              <% @closed_topics.each do |topic| %>
                  <li><%= topic.title %></li>
              <% end %>
            </ul>
        <% end %>
      </div>

    </div>
  </div>

  <div class="col s12 m6">
    <div id="map" style="width: 100%; height: 315px;"></div>
  </div>

</div>

app/views/trips/_trip_detail_header.html.erb
<div class="trip-details">
  <div class="row">
    <div class="col s12 m6">
      <div class="trip-detail-title">
        <h5 class="trip-headline"><%= @trip.name %></h5>
        <h6 class="trip-destination">
          <i class="material-icons" style="margin-right: 5px;">location_on</i>
          <%= @trip.destination %>
        </h6>
        <h6><%= t('organized_by') %>: <%= @trip.get_host_full_name %></h6>
        <hr>
        <div class="trip-detail-buttons">
          <% if policy(@trip).edit? %>
              <a href="<%= edit_trip_path(@trip) %>" style="margin-right: 20px;" class="tooltipped" data-position="top" data-delay="50" data-tooltip="<%= t('edit_trip') %>">
                <i class="material-icons card-icon">mode_edit</i>
              </a>
          <% end %>
          <% if policy(@trip).leave? %>
              <a href="<%= leave_trip_path(@trip) %>" style="margin-right: 20px;" class="tooltipped" data-position="top" data-delay="50" data-tooltip="<%= t('leave_trip') %>">
                <i class="material-icons">exit_to_app</i>
              </a>
          <% end %>
          <% if policy(@trip).invite? %>
              <div class="invitation-button tooltipped" style="margin-right: 20px;" data-target="invitation-modal" data-position="top" data-delay="50" data-tooltip="<%= t('invite_user') %>">
                <i class="material-icons">insert_invitation</i>
              </div>
          <% end %>
          <% if policy(@trip).destroy? %>
              <%= link_to @trip, method: :delete do %>
                  <i class="material-icons card-icon">delete</i>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col s12 m6">
      <div class="trip-detail-actions">
        <h5 class="trip-headline"><%= t('participants') %></h5>
        <div class="trip-detail-participant">
          <% @trip.trip_participants.each do |trip_participant| %>
              <div class="avatar avatar-bordered">
                <%= trip_participant.user.render_initials %>
              </div>
          <% end %>
        </div>

        <% if @trip.get_trip_invites.empty? %>
          <div class="trip-detail-participant-not-confirmed">
            <%= t('all_confirmed') %>
          </div>
        <% else %>
          <div class="trip-detail-participant-not-confirmed tooltipped" data-position="top" data-delay="50" data-tooltip="<%= @trip.get_pending_invites_email.html_safe if !@trip.get_pending_invites_email.nil? %>">
            <%= t('not_confirmed_participants') %> : <%= @trip.get_trip_invites.count %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/trips/_trip_details.html.erb
<!--Trip Detail Header-->

<%= render 'trip_detail_header' %>

<!--Trip Date Survey and Summary-->

<%= render 'trip_detail_body' %>

<!--Invitation Modal-->

<%= render 'invitation_modal', trip: @trip, invite: @invite  %>

<%= content_for :js do %>
    <%= javascript_tag do %>

        $(document).ready(function(){
          $('ul.tabs').tabs();
          $('ul.tabs').tabs('select_tab', 'tab_id');
          $('.modal').modal();

        var handler = Gmaps.build('Google');
        handler.buildMap({ internal: { id: 'map' } }, function() {
          markers = handler.addMarkers(<%= raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          if (markers.length == 0) {
              handler.getMap().setZoom(2);
          } else if (markers.length == 1) {
              handler.getMap().setZoom(14);
          }
          });
        });
    <% end %>
<% end %>

app/views/trips/_trip_expenses.html.erb
<h5 class="trip-headline"><%= t('expenses') %></h5>
<div class="container">
  <div class="row">
    <div class="col s12" id="trip-expense-total">
      <h5><%= t('total_expense') %></h5>
      <h5 style="margin-left: 10px;"><%= @total %> <%= t('currency') %></h5>
    </div>
  </div>
</div>

<% if @total > 0 %>
  <div>
    <% @participants.each do |participant| %>
        <%= render 'user_balance', participant: participant %>
    <% end %>

    <% @expenses.each do |ower, debts| %>
        <% debts.each do |debt| %>
          <%= render 'balance_expense', ower: ower.get_user_full_name, recipient: debt.first.get_user_full_name, amount: debt.last.round(1) %>
        <% end %>
    <% end %>
  </div>
<% end %>

app/views/trips/_trip_organization.html.erb
<div class="row">
  <div class="col s12 m6">
    <div class="trip-organization-container">
      <div class="trip-organization-title">
        <h5 class="trip-headline"><%= t('topics.topics') %></h5>
        <div class="fixed-action-btn horizontal">
          <%= link_to new_trip_topic_path(@trip, @survey), class: "btn-floating btn-medium indianred" do %>
            <i class="material-icons">add</i>
          <% end %>
          <ul>
            <li><a class="topic-button btn-floating red" value="Housing"><i class="material-icons">home</i></a></li>
            <li><a class="topic-button btn-floating yellow darken-1" value="Transport"><i class="material-icons">flight_takeoff</i></a></li>
            <li><a class="topic-button btn-floating green" value="Visit"><i class="material-icons">visibility</i></a></li>
          </ul>
        </div>
      </div>

      <div class="trip-topics">
        <% if @trip.survey %>
          <div class="topic-card">
            <div class="topic-card-title">
              <%= link_to t('date'), edit_topic_path(@survey), style: "margin-left: 15px;" %>
            </div>
            <%= render 'surveys/survey', survey: @survey, survey_dates: @survey_dates %>
          </div>

        <% end %>
        <% @pending_topics.each do |topic| %>
          <%= render 'topics/topic_card', topic: topic %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col s12 m6">
    <div class="trip-organization-container">
      <%= render 'trips/trip_expenses' %>
    </div>
  </div>

</div>

<%= content_for :js do %>
    <%= javascript_tag do %>

        $('.topic-button').click(function(){
          $.ajax({
              url: "<%= trip_create_auto_path(@trip) %>",
              type: "GET",
              data: { topic_type: $(this).attr('value') },
              success: function(data){
              },
              error: function(jqXHR) {
                  console.error(jqXHR.responseText);
              }
          });
        });

        $('.suggestion-vote-button').on("click", function(){
          $.ajax({
            type: "GET",
            url: "<%= vote_path %>",
            data: { suggestion_id: $(this).attr('suggestion_id') },
            success: function(data){
              var suggestionId = data.suggestion.id;
              var numberOfVotes = data.number_of_votes;
              var htmlListOfVoters = data.html_list_of_voters;
              var selector = '#suggestion_id_' + suggestionId
              $(selector).find('div').text(numberOfVotes);
              var popoverSelector = '#suggestion-popover-' + suggestionId;
              $(popoverSelector).html("");
              $(popoverSelector).append(htmlListOfVoters);
            },
            error: function(jqXHR) {
              console.error(jqXHR.responseText);
            }
          });
        });

        $('.number-votes-button-popover').hide();

        $('.suggestion-number-button').mouseenter(function(){
          var id = $(this).attr('suggestion_id');
          var selector = '#suggestion-popover-' + id;
          $(selector).show();
        });

        $('.suggestion-number-button').mouseleave(function(){
          var id = $(this).attr('suggestion_id');
          var selector = '#suggestion-popover-' + id;
          $(selector).hide();
        });

    <% end %>
<% end %>

app/views/trips/_user_balance.html.erb
<div class="container">
  <div class="row" style="margin-bottom: 5px;">
    <div class="col s12 trip-expense-user">
      <div class="trip-expense-user-name">
        <%= participant.get_user_full_name %>
      </div>
      <div class="trip-expense-user-balance progress">
        <% length = (participant.compute_user_balance(@trip, @total) / @total) * 100 %>
        <% if length >= 0 %>
          <div class="determinate success-progress-bar" style="width: <%= length.round %>%;">
            <%= participant.compute_user_balance(@trip, @total).round(1) %>
          </div>
        <% else %>
          <div class="determinate error-progress-bar" style="width: <%= ( - length ).round %>%;">
            <%= participant.compute_user_balance(@trip, @total).round(1) %>
          </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/trips/destroy.js.erb
$('#trip-id-<%= @trip.id %>').slideUp();

app/views/trips/index.html.erb
<div class="container">
  <div class="row">
    <% if @trips.empty? && @invitations.empty? %>
      <div class="col l6 s12 offset-l3">
        <div class="trip-container">
          <% if @mytrips.empty? %>
            <div class="no-trip-warning">
              <i class="fa fa-frown-o" aria-hidden="true"></i>
              <h5><%= t('trip.no_trip_information') %></h5>
              <br>
              <%= link_to t('create_trip'), new_trip_path, class: "waves-effect waves-light btn" %>
            </div>
          <% else %>
            <h5 class="trip-headline"><%= t('my_trips') %></h5>
            <% @mytrips.each do |trip| %>
                <%= render 'trip_card', trip: trip %>
            <% end %>
        <% end %>
        </div>
      </div>
    <% elsif @invitations.empty? && !@trips.empty? %>
        <div class="col l5 s12 offset-l1">
          <div class="trip-container">
            <% if @mytrips.empty? %>
                <div class="no-trip-warning">
                  <i class="fa fa-frown-o" aria-hidden="true"></i>
                  <h5><%= t('trip.no_trip_information') %></h5>
                  <br>
                  <%= link_to t('create_trip'), new_trip_path, class: "waves-effect waves-light btn" %>
                </div>
            <% else %>
                <h5 class="trip-headline"><%= t('my_trips') %></h5>
                <% @mytrips.each do |trip| %>
                    <%= render 'trip_card', trip: trip %>
                <% end %>
            <% end %>
          </div>
        </div>

        <div class="col l5 s12 offset-l1">
          <div class="trip-container">
            <% if @trips.empty? %>
                <div class="no-trip-warning">
                  <h5><%= t('trip.no_trip_information') %></h5>
                  <br>
                </div>

            <% else %>
                <h5 class="trip-headline"><%= t('my_invitation_trips') %></h5>
                <% @trips.each do |trip| %>
                    <%= render 'trip_card', trip: trip %>
                <% end %>
            <% end %>
          </div>
        </div>

    <% elsif !@invitations.empty? && @trips.empty? %>

        <div class="col l5 s12 offset-l1">
          <div class="trip-container">
            <% if @mytrips.empty? %>
                <div class="no-trip-warning">
                  <i class="fa fa-frown-o" aria-hidden="true"></i>
                  <h5><%= t('trip.no_trip_information') %></h5>
                  <br>
                  <%= link_to t('create_trip'), new_trip_path, class: "waves-effect waves-light btn" %>
                </div>
            <% else %>
                <h5 class="trip-headline"><%= t('my_trips') %></h5>
                <% @mytrips.each do |trip| %>
                    <%= render 'trip_card', trip: trip %>
                <% end %>
            <% end %>
          </div>
        </div>

        <div class="col l5 s12 offset-l1 ">
          <div class="trip-container">
            <h5 class="trip-headline"><%= t('my_invitations') %></h5>
            <% @invitations.each do |invitation| %>
                <%= render 'invitation_card', invitation: invitation %>
            <% end %>
          </div>
        </div>

    <% else %>
        <div class="col l5 s12">
          <div class="trip-container">
            <% if @mytrips.empty? %>
                <div class="no-trip-warning">
                  <i class="fa fa-frown-o" aria-hidden="true"></i>
                  <h5><%= t('trip.no_trip_information') %></h5>
                  <br>
                  <%= link_to t('create_trip'), new_trip_path, class: "waves-effect waves-light btn" %>
                </div>
            <% else %>
                <h5 class="trip-headline"><%= t('my_trips') %></h5>
                <% @mytrips.each do |trip| %>
                    <%= render 'trip_card', trip: trip %>
                <% end %>
            <% end %>
          </div>
        </div>

        <div class="col l4 s12 ">
          <div class="trip-container">
            <h5 class="trip-headline"><%= t('my_invitation_trips') %></h5>
            <% @trips.each do |trip| %>
                <%= render 'trip_card', trip: trip %>
            <% end %>
          </div>
        </div>

        <div class="col l3 s12 ">
          <div class="trip-container">
            <h5 class="trip-headline"><%= t('my_invitations') %></h5>
            <% @invitations.each do |invitation| %>
                <%= render 'invitation_card', invitation: invitation %>
            <% end %>
          </div>
        </div>

    <% end %>
  </div>
</div>

app/views/trips/new.html.erb
<div class="container">
  <div class="row">
    <div class="col l6 offset-l3 m8 offset-m2 s12 ">
      <div class="form-container">
        <div class="form-header">
          <h3><%= t('create_trip') %></h3>
        </div>
        <div class="form-body">
          <%= simple_form_for @trip do |f| %>
              <%= f.input :name %>
              <%= f.label :destination, required: true %>
              <%= f.input :destination, label: false %>
              <div id="trip-dates">
                <div class="form-dates">
                  <div class="input-field label">
                    <%= f.label :start_date, required: true %>
                    <%= f.text_field :start_date, multiple: true, class: "datepicker start_date", id: "start_date_picker_1" %>
                  </div>
                  <i class="material-icons">trending_flat</i>
                  <div class="input-field label">
                    <%= f.label :end_date, required: true %>
                    <%= f.text_field :end_date, multiple: true, class: "datepicker", id:"end_date_picker_2" %>
                  </div>
                  <i class="material-icons add-date-button clickable tooltipped" data-position="top" data-delay="100" data-tooltip="<%= t('survey.survey_question') %>">add_circle_outline</i>
                </div>
                <div id="survey">
                </div>
              </div>

              <div class="form-actions">
                <%= f.submit t('create_trip'), class: "waves-effect waves-light btn" %>
                <%= link_to t('back'), trips_path, class: "waves-effect waves-light btn" %>
              </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<!--Google autocomplete-->

<%= content_for :js do %>
    <%= javascript_tag do %>
        $(document).ready(function(){
          activateDatePicker();
          var start_date = nextWeekEndDate(new Date());
          var end_date = addDaysToDate(start_date, 2);
          var start_date_picker = $('#start_date_picker_1').pickadate('picker');
          start_date_picker.set ('select', start_date);
          var end_date_picker = $('#end_date_picker_2').pickadate('picker');
          end_date_picker.set ('select', end_date);
          $('#survey').hide();
        });


        $('.add-date-button').on("click", function(){

            var formDates = $('.form-dates').html();
            var newDateField = '<div class="form-dates">' + formDates + '</div>';
            $('#survey').append(newDateField).show('slow');
            $('.add-date-button').last().text("remove_circle_outline").removeClass('add-date-button').addClass('remove-date-button');
            activateDatePicker();
            $('.remove-date-button').on("click", function(){
                if ($('#survey .form-dates').length > 1) {
                    $('#survey .form-dates').last().remove();
                } else {
                    $('#survey').slideUp();
                    $('#survey .form-dates').last().remove();
                }
            });
        });

    <% end %>
<% end %>