config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :users do
    get 'sign_in', to: 'users/sessions#new'
  end

  root 'pages#homepage'

  resources :trips do
    resources :topics, only:[:new, :create]
    get 'leave', on: :member
    get 'create_auto', to: "topics#create_auto"

    resources :invites, only:[:new, :create] do
      get 'confirm', on: :member
      get 'decline', on: :member
    end
  end

  resources :surveys, only:[:show, :destroy] do
    member do
      get 'vote'
      get 'set_deadline'
      post 'send_deadline'
    end
  end

  resources :topics, only:[:edit, :update, :destroy] do
    member do
      get 'confirm'
      get 'get_suggestion'
    end
    resources :suggestions, only:[:new, :create, :destroy, :edit, :update]
  end

  get 'vote', to: "suggestions#vote"

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :trip
  has_many :suggestions, dependent: :destroy
  has_one :suggestion, dependent: :destroy

  def sort_suggestions_by_vote
    self.suggestions.sort_by { |suggestion| suggestion.votes_for.size }.reverse!
  end

  def find_winning_suggestion
    self.suggestions.sort_by { |suggestion| suggestion.votes_for.size }.reverse.first
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :set_trip, only: [:new, :create]
  before_action :set_topic, only: [:edit, :update, :destroy, :confirm]

  def new
    @topic = Topic.new
    authorize @topic
  end

  def create
    @topic = Topic.new(topic_params)
    authorize @topic
    @topic.trip = @trip
    @topic.status = "Pending"
    if @topic.save
      redirect_to trip_path(@trip, anchor: "organization")
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to trip_path(@topic.trip, anchor: "organization")
    else
      render :edit
    end
  end

  def destroy
    @topic.destroy
    redirect_to trip_path(@topic.trip, anchor: "organization")
  end

  def confirm
    @topic = Topic.find(params[:id])
    @suggestions = @topic.sort_suggestions_by_vote
    @suggestion = @topic.find_winning_suggestion
    # Lead to suggestions#update
  end

  def create_auto
    topic_type = params[:topic_type]
    @topic = Topic.create(title: topic_type, user_id: current_user.id, trip_id: @trip.id, status: "Pending")
    respond_to do |format|
      format.js
    end
  end

  def get_suggestion
    @topic = Topic.find(params[:id])
    authorize @topic
    @suggestion = Suggestion.find(params[:suggestion_id])
    respond_to do |format|
      format.js
    end
  end

  private

  def set_trip
    @trip = Trip.find(params[:trip_id])
  end

  def set_topic
    @topic = Topic.find(params[:id])
    authorize @topic
  end

  def topic_params
    params.require(:topic).permit(:title, :description)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_topic_card.html.erb
<div class="topic-card">
  <div class="topic-body">

    <div class="topic-card-title">
      <%= link_to topic.title, edit_topic_path(topic) %>
      <div class="topic-card-owner">
        <%= t('topics.created_by') %> <%= current_user.get_user_full_name %>
      </div>
    </div>



    <div class="topic-line-header"">
      <div>
      </div>
      <div class="topic-line-header-vote">
        <%= t('survey.number_of_votes') %>
      </div>
      <div class="topic-line-header-title">
        <div>
          <%= t('suggestions.name') %>
        </div>
        <div>
          <%= t('suggestions.price') %>
        </div>
      </div>
    </div>

    <% topic.suggestions.each do |suggestion| %>
      <%= render "suggestions/show", suggestion: suggestion %>
    <% end %>

    <div class="topic-card-actions">
      <% if !topic.suggestions.empty? %>
        <%= link_to t('topics.close_topic'), confirm_topic_path(topic), class: "waves-effect waves-light btn" %>
      <% end %>
      <%= link_to t('topics.add_suggestion'), new_topic_suggestion_path(topic, Suggestion.new), class: "waves-effect waves-light btn" %>
    </div>
  </div>
</div>

app/views/topics/confirm.html.erb
<div class="container">
  <div class="row">
    <div class="col l6 offset-l3 m8 offset-m2 s12 ">
      <div class="form-container">
        <div class="form-header">
          <h3><%= t('topics.close_topic') %></h3>
        </div>
        <div class="form-body">
          <div class="row">
            <div class="col s12">
              <div class="topic-line-header"">
                <div>
                </div>
                <div class="topic-line-header-vote">
                  <%= t('survey.number_of_votes') %>
                </div>
                <div class="topic-line-header-title">
                  <div>
                    <%= t('suggestions.name') %>
                  </div>
                  <div>
                    <%= t('suggestions.price') %>
                  </div>
                </div>
              </div>

              <% @suggestions.each do |suggestion| %>
                  <%= render "suggestions/suggestion_list", suggestion: suggestion %>
              <% end %>
            </div>

            <div class="col s12" id="winning-suggestion">
              <%= render 'suggestions/suggestion_form', topic: @topic, suggestion: @suggestion %>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<%= content_for :js do %>
    <%= javascript_tag do %>

      $('.suggestion-line').click(function(){
        $.ajax({
          url: "<%= get_suggestion_topic_path(@topic) %>",
          type: "GET",
          data: { suggestion_id: $(this).find('input').attr('suggestion_id') },
          success: function(data){
          },
          error: function(jqXHR) {
            console.error(jqXHR.responseText);
          }
        });
      });


      $('.number-votes-button-popover').hide();

      $('.suggestion-number-button').mouseenter(function(){
      var id = $(this).attr('suggestion_id');
      var selector = '#suggestion-popover-' + id;
      $(selector).show();
      });

      $('.suggestion-number-button').mouseleave(function(){
      var id = $(this).attr('suggestion_id');
      var selector = '#suggestion-popover-' + id;
      $(selector).hide();
      });

    <% end %>
<% end %>

app/views/topics/create_auto.js.erb
var topicCard = $("<%= j render 'topics/topic_card', topic: @topic %>").hide();

$('.trip-topics').prepend(topicCard);

topicCard.slideDown();

app/views/topics/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col l6 offset-l3 m8 offset-m2 s12 ">
      <div class="form-container">
        <div class="form-header">
          <h3><%= t('topics.edit_topic') %></h3>
        </div>
        <div class="form-body">
          <%= simple_form_for [@topic] do |f| %>
              <%= f.input :title %>
              <%= f.input :description%>


              <div class="form-actions">
                <%= f.submit t('topics.edit_topic'), class: "waves-effect waves-light btn" %>
                <%= link_to t('back'), trip_path(@topic.trip), class: "waves-effect waves-light btn" %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/topics/get_suggestion.js.erb
var suggestion = $("<%= j render 'suggestions/suggestion_form', topic: @topic, suggestion: @suggestion %>").hide();

$('#winning-suggestion').html("");
$('#winning-suggestion').prepend(suggestion);

suggestion.show();

app/views/topics/new.html.erb
<div class="container">
  <div class="row">
    <div class="col l6 offset-l3 m8 offset-m2 s12 ">
      <div class="form-container">
        <div class="form-header">
          <h3><%= t('topics.create_topic') %></h3>
        </div>
        <div class="form-body">
          <%= simple_form_for [@trip, @topic] do |f| %>
              <%= f.input :title %>
              <%= f.input :description%>


              <div class="form-actions">
                <%= f.submit t('topics.create_topic'), class: "waves-effect waves-light btn" %>
                <%= link_to t('back'), trip_path(@trip, anchor: "organization"), class: "waves-effect waves-light btn" %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>