config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  devise_scope :users do
    get 'sign_in', to: 'users/sessions#new'
  end

  root 'pages#homepage'

  resources :trips do
    resources :topics, only:[:new, :create]
    get 'leave', on: :member
    get 'create_auto', to: "topics#create_auto"

    resources :invites, only:[:new, :create] do
      get 'confirm', on: :member
      get 'decline', on: :member
    end
  end

  resources :surveys, only:[:show, :destroy] do
    member do
      get 'vote'
      get 'set_deadline'
      post 'send_deadline'
    end
  end

  resources :topics, only:[:edit, :update, :destroy] do
    member do
      get 'confirm'
      get 'get_suggestion'
    end
    resources :suggestions, only:[:new, :create, :destroy, :edit, :update]
  end

  get 'vote', to: "suggestions#vote"

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :trip
  has_many :survey_dates, dependent: :destroy

  def sort_by_votes
    self.survey_dates.sort_by { |survey_date| survey_date.votes_for.size }.reverse!
  end

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  before_action :find_survey

  def show
    @survey_dates = @survey.sort_by_votes
  end

  def destroy
    @trip = @survey.trip
    authorize @trip
    @survey_date = @survey.sort_by_votes.first
    @trip.start_date = @survey_date.start_date
    @trip.end_date = @survey_date.end_date
    @trip.save
    @survey.destroy
    redirect_to trip_path(@trip)
  end

  def vote
    @survey_date = SurveyDate.find(params[:survey_date_id])
    if current_user.voted_up_on? @survey_date
      # Downvote Survey Date
      @survey_date.unliked_by current_user
      render json: {
          survey_date: @survey_date,
          number_of_votes: @survey_date.votes_for.size,
          html_list_of_voters: @survey_date.get_html_list_of_voters,
          message: "downvote"
      }
    else
      # Vote for survey date
      @survey_date.liked_by current_user
      render json: {
          survey_date: @survey_date,
          number_of_votes: @survey_date.votes_for.size,
          html_list_of_voters: @survey_date.get_html_list_of_voters,
          message: "vote"
      }
    end
  end

  private

  def find_survey
    @survey = Survey.find(params[:id])
    authorize @survey
  end
end

app/views/surveys/_survey.html.erb
<div class="survey-body survey-body-modal">
  <div class="survey-line-header" style="height: 50px;">
    <div>
    </div>
    <div class="survey-line-header-vote">
      <%= t('survey.number_of_votes') %>
    </div>
    <div class="survey-dates">
      <div>
        <%= t('date.start_date') %>
      </div>
      <div>
        <%= t('date.end_date') %>
      </div>
    </div>
  </div>
  <% survey_dates.each do |survey_date| %>
      <div class="survey-line survey-line-modal">
        <input name="group1" class="survey-vote-button" type="checkbox" <%= survey_date.voted_by?(current_user) ? 'checked' :"" %> id="<%= survey_date.id %>" />
        <label for="<%= survey_date.id %>"></label>

        <div class="btn-floating number-votes-button" survey_date_id="<%= survey_date.id %>" id="survey_date_button_<%= survey_date.id %>">
          <div class="number-votes-button-text">
            <%= survey_date.votes_for.size %>
          </div>
        </div>

        <% if survey_date.votes_for.size > 0 %>
            <div class="number-votes-button-popover" id="survey-popover-<%= survey_date.id %>">
              <%= survey_date.get_html_list_of_voters.html_safe %>
            </div>
        <% end %>

        <div class="survey-dates">
          <%= l(survey_date.start_date, format: :short) %>
          <i class="material-icons">trending_flat</i>
          <%= l(survey_date.end_date, format: :short) %>
        </div>
      </div>
  <% end %>
</div>

<div class="survey-actions" style="justify-content: center">
  <% if policy(survey).destroy? %>
      <%= link_to t('survey.close_survey'), survey, method: :delete, class: "btn" %>
  <% end %>
</div>



<%= content_for :js do %>
    <%= javascript_tag do %>

        $('.number-votes-button-popover').hide();

        $('.survey-vote-button').on("click", function(){
            $.ajax({
              type: "GET",
              url: "<%= vote_survey_path(survey) %>",
              data: { survey_date_id: $(this).attr('id') },
              success: function(data){
                var id = data.survey_date.id;
                var numberOfVotes = data.number_of_votes;
                var htmlListOfVoters = data.html_list_of_voters;
                var selector = '[survey_date_id =' + id + ']';
                $(selector).find('div').text(numberOfVotes);
                var popoverSelector = '#survey-popover-' + id;
                $(popoverSelector).html("");
                $(popoverSelector).append(htmlListOfVoters);
              },
              error: function(jqXHR) {
                console.error(jqXHR.responseText);
              }
            });
        });

        $('.number-votes-button').mouseenter(function(){
          var id = $(this).attr('survey_date_id');
          var selector = '#survey-popover-' + id;
          $(selector).show();
        });

        $('.number-votes-button').mouseleave(function(){
          var id = $(this).attr('survey_date_id');
          var selector = '#survey-popover-' + id;
          $(selector).hide();
        });

    <% end %>
<% end %>

app/views/surveys/show.html.erb
<div class="container">
  <div class="row">
    <div class="col l6 offset-l3 s12 ">
      <div class="survey-container">
        <div class="survey-header">
          <h3><%= @survey.trip.name %>'s survey</h3>
        </div>
        <div class="survey-body">
          <div class="survey-table">
            <div class="survey-line-header">
              <div>
              </div>
              <div>
                <%= t('survey.number_of_votes') %>
              </div>
              <div class="survey-dates">
                <div>
                  <%= t('date.start_date') %>
                </div>
                <div>
                  <%= t('date.end_date') %>
                </div>
              </div>
            </div>
            <% @survey_dates.each do |survey_date| %>
                <div class="survey-line">
                  <input name="group1" class="survey-vote-button" type="checkbox" <%= survey_date.voted_by?(current_user) ? 'checked' :"" %> id="<%= survey_date.id %>" />
                  <label for="<%= survey_date.id %>"></label>

                  <div class="btn-floating number-votes-button" survey_date_id="<%= survey_date.id %>" id="survey_date_button_<%= survey_date.id %>">
                    <div class="number-votes-button-text">
                      <%= survey_date.votes_for.size %>
                    </div>
                  </div>

                  <% if survey_date.votes_for.size > 0 %>
                    <div class="number-votes-button-popover" id="survey-popover-<%= survey_date.id %>">
                      <%= survey_date.get_html_list_of_voters.html_safe %>
                    </div>
                  <% end %>


                  <div class="survey-dates">
                    <%= l(survey_date.start_date, format: :short) %>
                    <i class="material-icons">trending_flat</i>
                    <%= l(survey_date.end_date, format: :short) %>
                  </div>
                </div>
            <% end %>
          </div>

          <div class="survey-actions">
            <%= link_to t('back'), trips_path, class: "btn" %>
            <% if policy(@survey).destroy? %>
                <%= link_to t('survey.close_survey'), @survey, method: :delete, class: "btn" %>
            <% end %>
          </div>
        </div>
      </div>
  </div>
</div>

  <%= content_for :js do %>
      <%= javascript_tag do %>
          $('.number-votes-button-popover').hide();

          $('.survey-vote-button').on("click", function(){
            $.ajax({
              type: "GET",
              url: "<%= vote_survey_path(@survey) %>",
              data: { survey_date_id: $(this).attr('id') },
              success: function(data){
                var id = data.survey_date.id;
                var numberOfVotes = data.number_of_votes;
                var htmlListOfVoters = data.html_list_of_voters;
                var selector = '[survey_date_id =' + id + ']'
                $(selector).find('div').text(numberOfVotes);
                var popoverSelector = '#survey-popover-' + id;
                $(popoverSelector).html("");
                $(popoverSelector).append(htmlListOfVoters);
                },
              error: function(jqXHR) {
                console.error(jqXHR.responseText);
              }
            });
          });

          $('.number-votes-button').mouseenter(function(){
            var id = $(this).attr('survey_date_id');
            var selector = '#survey-popover-' + id;
            $(selector).show();
          });

          $('.number-votes-button').mouseleave(function(){
            var id = $(this).attr('survey_date_id');
            var selector = '#survey-popover-' + id;
            $(selector).hide();
          });

      <% end %>
  <% end %>